const courses = [
  {
    id: "course512",
    name: "Master Your Brain: Personal Development",
    desc: "Anyone involved with others – at work or at home – who wants to tackle difficult behaviour more effectively will enjoy this course. It'll help you successfully settle those difficult interactions...",
    img: "https://unicoach.wgl-demo.net/wp-content/uploads/2020/09/courses_01-870x635.jpg",
    instructor: "Chriss Moore",
    tag: "LifeStyle",
    price: 512,
  },
  {
    id: "course510",
    name: "Finding Your Life’s Purpose by Eckhart Tolle",
    desc: "Anyone involved with others – at work or at home – who wants to tackle difficult behaviour more effectively will enjoy this course. It'll help you successfully settle those difficult interactions...",
    img: "https://unicoach.wgl-demo.net/wp-content/uploads/2020/09/courses_02-870x635.jpg",
    instructor: " Peter Power",
    tag: "Development",
    price: 510,
  },
  {
    id: "course513",
    name: "Personal Development Transformation Course",
    desc: "Anyone involved with others – at work or at home – who wants to tackle difficult behaviour more effectively will enjoy this course. It'll help you successfully settle those difficult interactions...",
    img: "https://unicoach.wgl-demo.net/wp-content/uploads/2020/09/courses_03-870x635.jpg",
    instructor: "Arnold Ozix",
    tag: "Health",
    price: 610,
  },
  {
    id: "course514",
    name: "The Daily Journal – Habit of Successful People",
    desc: "Anyone involved with others – at work or at home – who wants to tackle difficult behaviour more effectively will enjoy this course. It'll help you successfully settle those difficult interactions...",
    img: "https://unicoach.wgl-demo.net/wp-content/uploads/2020/09/courses_04-870x635.jpg",
    instructor: "Katrin Perish",
    tag: "Business",
    price: 511,
  },
];
